// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSeGAk1nUq-YXNYqd-vrQjJ5YuxoQoF_A',
    appId: '1:341387419489:web:5a8df3fdee861366ea6f20',
    messagingSenderId: '341387419489',
    projectId: 'unite-a97de',
    authDomain: 'unite-a97de.firebaseapp.com',
    storageBucket: 'unite-a97de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl3fsXlrOHVlzI5GRw1DGKu35o9V0ycM8',
    appId: '1:341387419489:android:a1ebf5369917a6b2ea6f20',
    messagingSenderId: '341387419489',
    projectId: 'unite-a97de',
    storageBucket: 'unite-a97de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK959bxwW_kerENcYGZpkMIladw28tQec',
    appId: '1:341387419489:ios:b604592a5df93265ea6f20',
    messagingSenderId: '341387419489',
    projectId: 'unite-a97de',
    storageBucket: 'unite-a97de.appspot.com',
    iosBundleId: 'com.example.unite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK959bxwW_kerENcYGZpkMIladw28tQec',
    appId: '1:341387419489:ios:b604592a5df93265ea6f20',
    messagingSenderId: '341387419489',
    projectId: 'unite-a97de',
    storageBucket: 'unite-a97de.appspot.com',
    iosBundleId: 'com.example.unite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSeGAk1nUq-YXNYqd-vrQjJ5YuxoQoF_A',
    appId: '1:341387419489:web:b6b1b9d451e53fc3ea6f20',
    messagingSenderId: '341387419489',
    projectId: 'unite-a97de',
    authDomain: 'unite-a97de.firebaseapp.com',
    storageBucket: 'unite-a97de.appspot.com',
  );
}
