// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAooRFwlhB0eWhZoRpnUyPpItzHCVqXMKU',
    appId: '1:652203000256:web:8f5a9a6fabcea408a3c825',
    messagingSenderId: '652203000256',
    projectId: 'unite-b2c55',
    authDomain: 'unite-b2c55.firebaseapp.com',
    databaseURL: 'https://unite-b2c55-default-rtdb.firebaseio.com',
    storageBucket: 'unite-b2c55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6NlbbXSJXEUFPsR2QEvzMRz9yf7vLgBY',
    appId: '1:652203000256:android:13f831ca7ec018efa3c825',
    messagingSenderId: '652203000256',
    projectId: 'unite-b2c55',
    databaseURL: 'https://unite-b2c55-default-rtdb.firebaseio.com',
    storageBucket: 'unite-b2c55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPrdxpa5u7y0qcpcHTytqWL1Y5i7ajnyQ',
    appId: '1:652203000256:ios:cd7c38330264ddfea3c825',
    messagingSenderId: '652203000256',
    projectId: 'unite-b2c55',
    databaseURL: 'https://unite-b2c55-default-rtdb.firebaseio.com',
    storageBucket: 'unite-b2c55.appspot.com',
    iosBundleId: 'com.example.unite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPrdxpa5u7y0qcpcHTytqWL1Y5i7ajnyQ',
    appId: '1:652203000256:ios:cd7c38330264ddfea3c825',
    messagingSenderId: '652203000256',
    projectId: 'unite-b2c55',
    databaseURL: 'https://unite-b2c55-default-rtdb.firebaseio.com',
    storageBucket: 'unite-b2c55.appspot.com',
    iosBundleId: 'com.example.unite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAooRFwlhB0eWhZoRpnUyPpItzHCVqXMKU',
    appId: '1:652203000256:web:8f5a9a6fabcea408a3c825',
    messagingSenderId: '652203000256',
    projectId: 'unite-b2c55',
    authDomain: 'unite-b2c55.firebaseapp.com',
    databaseURL: 'https://unite-b2c55-default-rtdb.firebaseio.com',
    storageBucket: 'unite-b2c55.appspot.com',
  );

}